---
- hosts: ui
  roles:
    - role: sslcerts
      ssl_certs_generate_dh_param: true
      ssl_certs_path_owner: "root"
      ssl_certs_path_group: "root"
      ssl_certs_common_name: "{{ansible_fqdn}}"
    - role: nginx
      nginx_configs:
        ssl:
          - ssl_certificate_key {{ssl_certs_privkey_path}}
          - ssl_certificate     {{ssl_certs_cert_path}}
          - ssl_dhparam         {{ssl_certs_dhparam_path}}
      nginx_sites:
        default:
          - listen 443 ssl
          - server_name _
          - root "/usr/share/nginx/html"
          - index index.html
      nginx_http_params:
        - sendfile "on"
        - tcp_nopush "on"
        - tcp_nodelay "on"
        - keepalive_timeout "65"
        - access_log "/var/log/nginx/access.log"
        - error_log "/var/log/nginx/error.log"
        - server_tokens off
        - types_hash_max_size 2048
        - client_max_body_size "3M"
      nginx_daemon_mode: "off"
  tasks:
    - name: Include Main tasks
      include_tasks: ./tasks/main.yml
    - name: Install dumb init
      get_url:
        dest: /usr/bin/dumb-init
        url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
        mode: 0775
        validate_certs: no
    - name: Add RuleChains Repo
      yum_repository:
        name: "{{ rulechainsrepo.name }}"
        description: "{{ rulechainsrepo.name }}"
        baseurl: "{{ rulechainsrepo.baseurl }}"
        gpgcheck: "{{ rulechainsrepo.gpgcheck }}"
        repo_gpgcheck: "{{ rulechainsrepo.repo_gpgcheck }}"
        enabled: "{{ rulechainsrepo.enabled }}"
        metadata_expire: "{{ rulechainsrepo.metadata_expire }}"
    - name: install the latest version of RuleChains
      package:
        name: RuleChains-UI
        state: latest
    - name: install the latest updates
      package:
        name: "*"
        state: latest 
