---
- hosts: ui
  tasks:
    - name: Include Main tasks
      include_tasks: ./tasks/main.yml
    - name: Install dumb init
      get_url:
        dest: /usr/bin/dumb-init
        url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
        mode: 0775
        validate_certs: no
    - name: Add RuleChains Repo
      yum_repository:
        name: "{{ rulechainsrepo.name }}"
        description: "{{ rulechainsrepo.name }}"
        baseurl: "{{ rulechainsrepo.baseurl }}"
        gpgcheck: "{{ rulechainsrepo.gpgcheck }}"
        repo_gpgcheck: "{{ rulechainsrepo.repo_gpgcheck }}"
        enabled: "{{ rulechainsrepo.enabled }}"
        metadata_expire: "{{ rulechainsrepo.metadata_expire }}"
    - name: install the latest version of RuleChains
      package:
        name: RuleChains-UI
        state: latest
    - name: install the latest updates
      package:
        name: "*"
        state: latest 
