# Install Ansible Roles
# ---------------------
# When making the Conductor image `ansible-galaxy install -r requirements.yml` is executed
# using this file. Follow the instructions at http://docs.ansible.com/ansible/galaxy.html
# to include any roles you want installed prior to running main.yml.
- src: geerlingguy.repo-epel
  version: 1.2.2
  name: repo-epel
- src: jdauphant.ssl-certs
  version: v1.4
  name: sslcerts
- src: jdauphant.nginx
  version: v2.15.2
  name: nginx
