---
- name: Ensure the fpm gem installed
  command: gem install fpm
- name: remove node_modules and dist folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ../node_modules
    - ../dist
- name: Build RuleChainsUI
  shell: "{{ item }}"
  with_items:
    - "npm install"
    - "node_modules/@angular/cli/bin/ng build --prod --build-optimizer"
  args:
      chdir: "../"
- name: Build RuleChainsUI RPM
  shell: "fpm -s dir -t rpm -n {{ app_name | quote }} -v {{ package_settings.version | quote }} --iteration {{ package_revision | quote }} --description {{ ('YMD RuleChains-UI - ' ~ package_settings.description) | quote }} --vendor {{ 'YMD Partners' | quote }} -d {{ 'nginx' | quote }} -d {{ 'nodejs' | quote }} dist/.=/usr/local/lib/rulechains/ui"
  args:
      chdir: "../"

