---
- name: Ensure the fpm gem installed
  command: gem install fpm
- name: remove node_modules and dist folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ../node_modules
    - ../dist
- name: Build RuleChainsUI
  shell: "{{ item }}"
  with_items:
    - "npm install"
    - "node_modules/@angular/cli/bin/ng build -prod"
  args:
      chdir: "../"

