---
#- name: pull image
#  docker_image:
#    name: fedora:26
#    state: present
#- name: create docker container
#  docker_container:
#    name: RuleChains
#    image: ubuntu
#    state: started
#    recreate: yes
#    exposed_ports:
#      - 80
#    ports:
#      - "80:9080"
#- name: Ensure the fpm gem installed
#  command: gem install fpm
- name: Install (virtualenv) within a user home directory.
  pip:
    name: virtualenv
    extra_args: --user
- name: Setup the requirements for container
  pip:
    requirements: requirements.txt
    virtualenv: "{{ playbook_dir }}/libs"
    chdir: ../
#- name: virtualenv activate
#  shell: "source {{ playbook_dir }}/libs/bin/activate"
#- name: build docker
#  shell: "{{ playbook_dir }}/libs/bin/ansible-container --debug build"
#  args:
#    chdir: "{{ playbook_dir }}/docker"
- name: create package folder
  file:
    path: /tmp/debs
    state: "{{ item }}"
  with_items:
    - absent
    - directory
  tags:
    - deploy
- name: Copy package to remote host
  copy:
    src: "{{ item }}"
    dest: /tmp/debs
  with_fileglob:
    - "../rulechains*.deb"
  tags:
    - deploy
- name: Find the rulechains package that was produced
  find:
    paths: "/tmp/debs"
    patterns: "rulechains*.deb"
  register: iffind
  tags:
    - deploy
- name: Install a rulechains .deb package
  apt:
    deb: "{{ item.path }}"
  with_items: "{{ iffind.files|default([]) }}"
  register: rc_result
  tags:
    - deploy
- name: install the latest updates
  package:
    name: "*"
    state: latest
    force_apt_get: True
  tags:
    - deploy

