---
- name: pull image
  docker_image:
    name: ubuntu
    state: present
- name: create docker container
  docker_container:
    name: RuleChains
    image: ubuntu
    state: started
    recreate: yes
    exposed_ports:
      - 80
    ports:
      - "80:80"